### ISSUE TITLE
Make default graph definitions consistent between Jena and Corese

### ISSUE THREAD

**Issue by remiceres** [Wimmics/corese#102]
Adaptation of the JenaDataManager to make the default graph definitions consistent between Jena and Corese.

**Objective:** To pass the tests of the file JenaDataManagerTest.java

**Comment by remiceres** [comment]
Fix here : e1b8c29ae5640819ef1b687e2efab4d0b1ae951e

**Comment by ocorby** [comment]
Hello, 

pb pour interroger un graphe nommé kg:rule 

from named kg:rule graph ?g { ?s ?p ?o} ne marche pas 
graph kg:rule {?s ?p ?o} ne marche pas 
from kg:rule where {?s ?p ?o} marche 

Par ailleurs, quand on charge des documents dans kg:default, ça construit le graphe par défaut et sparql query marche. 
Mais dans ce cas, graph ?g { } ne doit pas retourner les triplets du graphe par défaut (ce qui est le cas) 

Olivier
