### ISSUE TITLE
Default namespaces

### ISSUE THREAD

**Issue by echo66** [Wimmics/corese#11]
Greetings!

How do I define the default namespaces to be used in kgserver? For example, rdfs, xsd, rdf and owl are already default namespaces in every SPARQL query.

**Comment by ocorby** [comment]
On 02/08/2016 02:04 PM, echo66 wrote:
> How do I define the default namespaces to be used in kgserver? For 
> example, rdfs, xsd, rdf and owl are already default namespaces in 
> every SPARQL query.

QueryProcess.definePrefix("ex", "http://example.org/");



Olivier Corby

**Comment by echo66** [comment]
Is it supposed for owl, rdf, rdfs and xsd namespaces to be included in the same way? I'm asking this because I performed a text search with grep, _grep -R "definePrefix(" ._, in Corese root directory and I didn't find any entries for those 4 namespaces.

**Comment by ndelaforge** [comment]
Yes "rdf/rdfs/owl" prefixes are included by default.
You only have to declare your own specific prefixes the way Olivier told you.

Cheers.

**Comment by echo66** [comment]
Thanks for the clarification :+1:
