### ISSUE TITLE
Indicating the end of loading by a message in the System tab

### ISSUE THREAD

**Issue by FabienGandon** [Wimmics/corese#111]
Hello,

I witnessed that several users are waiting for the loading of datasets and schemas while they were immediately loaded.
They expect a message in the system tab saying the loading is finished and went well.
When there is a error we have messages and we should have one saying it is done when there was no error.

Cheers,

**Comment by remiceres** [comment]
Hi Fabien,

Thanks for the feedback. I've added your suggested feature in the latest 4.4.1 release. Now, when a graph is done loading, a "Load done" message will appear in the console. See attached photo for details.

![image](https://github.com/Wimmics/corese/assets/5692787/f6e11fd1-3982-48d2-bfb4-ae6fcc7e8139)

Best,
Rémi
