### ISSUE TITLE
SUBSTR

### ISSUE THREAD

**Issue by FabienGandon** [Wimmics/corese#116]
Hello

The following query should give me "ypr" for the rdf:type and "1","2", ... for the rdf:_1,...
but it doesn't

select * where
{
?x ?p ?y.
BIND ( SUBSTR(STR(?p), 45)  AS ?end) 
}

Cheers,

**Comment by ocorby** [comment]
Hello, 
It works for me. 
What result do you have ? 
Cheers

**Comment by FabienGandon** [comment]
it stops at 44 i.e. I have "type" and "_1" but can't get "ype" or "1"

**Comment by ocorby** [comment]
In SPARQL character range is 1..n and not 0..n-1
-------- Message d'origine --------De : Fabien Gandon ***@***.***> Date : 12/12/2022  22:15  (GMT+01:00) À : Wimmics/corese ***@***.***> Cc : ocorby ***@***.***>, Comment ***@***.***> Objet : Re: [Wimmics/corese] SUBSTR (Issue #116) 
it stops at 44 i.e. I have "type" and "_1" but can't get "ype" or "1"

**Comment by FabienGandon** [comment]
even with other values I can't get to "1" or "ype" or "pe"
