### ISSUE TITLE
add DESCRIBE to the QUERY menu of CORESE-GUI

### ISSUE THREAD

**Issue by FabienGandon** [Wimmics/corese#119]
The current options of the `QUERY` menu of CORESE-GUI do not include the `DESCRIBE `clause.
We could have two versions:

`DESCRIBE <http://my.resource.org/>`

and

```
DESCRIBE ?x
WHERE { ?x ?p ?v }
LIMIT 1
```

**Comment by remiceres** [comment]
Hello Fabien,

Thanks for our suggestion, I had these two `DESCRIBE` clauses in the `query` menu.

You will find this modification in the next version 4.4.0.
