### ISSUE TITLE
[Feature request] corese-command include a mode to query a remote endpoint

### ISSUE THREAD

**Issue by MaillPierre** [Wimmics/corese#135]
**Is your feature request related to a problem? Please describe.**
As corese-command can query the content of files, I would like to be able to use Corese to query remote endpoints in the command line.

This would be easier to integrate remote queries in scripts, uses corese inner SPARQL syntax check, and let corese handle the result format of endpoints that are not standard.

**Describe the solution you'd like**
A mode such as
```
corese-command remote -q "DESCRIBE <https://data.archives-ouvertes.fr/author/pierre-maillot>" -e "http://data.archives-ouvertes.fr/sparql"
```
returns the results of the query.

**Describe alternatives you've considered**
Right now, only Apache Fuseki proposes an alternative, or it is possible to use low-level commands such as wget or curl.

**Comment by remiceres** [comment]
Hi Pierre,

Good news! This feature is being developed in the "development" branch and will be available in the next release.
