### ISSUE TITLE
Configuration file available in Python library

### ISSUE THREAD

**Issue by NicoRobertIn** [Wimmics/corese#145]
**Is your feature request related to a problem? Please describe.**
I would like to provide a configuration file in Corese python library the same way it is already possible with CLI

**Describe the solution you'd like**
I could just call Corese jar in the subprocess with the same option than with GUI to provide my configuration file
The line would look like this:

```python
java_process = Popen(['java', '-jar', '-Dfile.encoding=UTF-8', 'corese-library-python-4.4.1.jar', '--config', 'config.properties'])
```

**Comment by remiceres** [comment]
Hello,

Thank you for this suggestion. I have added support for the `-c` option to add a Corese config file. You can find all available options with `-h`. This feature will be available in the next release of Corese (4.4.2).
