### ISSUE TITLE
Incremental Reasoning/Update?

### ISSUE THREAD

**Issue by echo66** [Wimmics/corese#15]
Greetings.

Does Corese drop all inferred triples at each new manually inserted/removed triple? Or does it perform some kind of incremental reasoning?

**Comment by ocorby** [comment]
Hello,

On 03/24/2016 09:58 PM, echo66 wrote:
> Does Corese drop all inferred triples at each new manually 
> inserted/removed triple? Or does it perform some kind of incremental 
> reasoning?
Previously inferred triples are kept unchanged upon update (unless 
explicitely updated !)
RDFS entailments are incremental
OWL RL can be tuned to be incremental : graph.addEngine(ruleEngine);

Regards

Olivier
