### ISSUE TITLE
Logger obsolete

### ISSUE THREAD

**Issue by ndelaforge** [Wimmics/corese#16]
Hello,

Est-il possible de mettre à jour le logger de Corese ?
La version qu'il embarque [date de 2012](http://mvnrepository.com/artifact/log4j/log4j) et n'est pas compatible avec les nouveaux frameworks de logging comme SLF4J ou Logback. Il a été remplacé par [cette version](http://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-core).

Je vous conseille de jeter un coup d'oeil sur [SLF4J](http://mvnrepository.com/artifact/org.slf4j/slf4j-api) ou [Logback Classic](http://mvnrepository.com/artifact/ch.qos.logback/logback-classic) qui sont bien plus faciles à paramétrer/étendre.

A bientôt

**Comment by ErwanDemairy** [comment]
Salut,
J'ai mis log4j2 dans la version courante.
Bonne journée,
