### ISSUE TITLE
[Bug] Corese-command sparql returns turtle with malformed prefixed URIs

### ISSUE THREAD

**Issue by MaillPierre** [Wimmics/corese#167]
**Issue Description:**

When confronted with unusual URIs in the results of a CONSTRUCT query, the turtle file returned by `corese-command sparql` contains a malformed URL.

**Steps to Reproduce:**
1. Create a file `test_data.ttl` containing:
```turtle
@prefix void: <http://rdfs.org/ns/void#> .

_:b0 void:sparqlEndpoint <https://allegro.callisto.calmip.univ-toulouse.fr/#/repositories/sms> .
```
2. Create a file `test_query.rq` containing:
```sparql
CONSTRUCT {
    ?s ?p ?o
}
WHERE {
    ?s ?p ?o
}
```
3. Execute  `java -jar corese-command-4.5.0.jar sparql -q test_query.rq -i test_data.ttl -o test_results.ttl`. `test_result.ttl` should contain:
```turtle
@prefix ns2: <https://allegro.callisto.calmip.univ-toulouse.fr/#> .
@prefix ns1: <http://rdfs.org/ns/void#> .

_:b0 ns1:sparqlEndpoint ns2:/repositories/sms .
```
4. (Optional) Execute `java -jar corese-command-4.5.0.jar sparql -q test_query.rq -i test_results.ttl` and you will receive an error: 
```
Error: Failed to parse RDF file. Check if file is well-formed and that the input format is correct. Encountered "/" at line 4, column 29.
Was expecting one of:
    <EOF> 
    <Q_IRIref> ...
```

**Expected Behavior:**
The result should be something like:

```turtle
@prefix ns2: <https://allegro.callisto.calmip.univ-toulouse.fr/#/repositories/> .
@prefix ns1: <http://rdfs.org/ns/void#> .

_:b0 ns1:sparqlEndpoint ns2:sms .
```

**Actual Behavior:**

This bug is observed in results containing the URL `<https://allegro.callisto.calmip.univ-toulouse.fr/#/repositories/sms>`. When it is returned in a turtle file, it is prefixed as `ns:/repositories/sms`.

**Note to Developers:**
In my understanding, the algorithm that decides how to generate prefixes is cutting the URI in priority are the last `#`. It should be modified to cut either at the lastest `#` or `/`.

**Comment by remiceres** [comment]
Hello Pierre, thank you for signaling the issue, this will be fixed in the next release.
