### ISSUE TITLE
Content not allowed in prolog {301}

### ISSUE THREAD

**Issue by rac021** [Wimmics/corese#19]
Hi, 

I'm using corese server in a Java project to infer new triples ; when I call  **loader.load("myOnto.owl")**  
I randomly get the error " Content not allowed in prolog {301} ". 

The ontology "myOnto.owl" imports other ontologies which are in RDF/XML format ( from the web ) .
 
I suspect that this error is due to the BOM ( Byte-Order-Mark ) which is not ignored when parsing the imported ontologies. 

Is there any way around this problem ?

Regards. Rachid.

**Comment by ocorby** [comment]
Hi,

" Content not allowed in prolog {301} " is a message from the RDF/XML 
parser that detects that the content is not correct RDF/XML.
Usually this problem occurs when  extension .rdf .rdfs .owl is used with 
files the content of which is not RDF/XML.
You may check the extension and the content of files you load.
If this is not the case you may send me the URL of the file that 
triggers this error.

Best regards

Olivier Corby

**Comment by rac021** [comment]
Hi ,
Thank you for your quick reponse,

In the follwing, the ontologies ( imported in myOnto.owl ) that triggers this error :
         http://ecoinformatics.org/oboe/oboe.1.0/oboe-core.owl
         http://ecoinformatics.org/oboe/oboe.1.0/oboe-spatial.owl
         http://ecoinformatics.org/oboe/oboe.1.0/oboe-standards.owl
         http://ecoinformatics.org/oboe/oboe.1.0/oboe-temporal.owl

it seems to be valid and correctly named. The strangest in all this is that I have not always this error, but only occasionally !

Regards

**Comment by ocorby** [comment]
Hi,

On 07/02/2016 09:07 PM, Yahiaoui Rachid wrote:
> n the follwing, the ontologies ( imported in myOnto.owl ) that 
> triggers this error :
> http://ecoinformatics.org/oboe/oboe.1.0/oboe-core.owl
> http://ecoinformatics.org/oboe/oboe.1.0/oboe-spatial.owl
> http://ecoinformatics.org/oboe/oboe.1.0/oboe-standards.owl
> http://ecoinformatics.org/oboe/oboe.1.0/oboe-temporal.owl

I loaded these ontologies without problem.
What OS do you use and wich Java version ?


Best regards

Olivier Corby

**Comment by rac021** [comment]
Hi,

 OS : **Debian 4.1.6-1** (2015-08-23) x86_64 GNU/Linux
 Java Version : **1.8.0_66**

The crazy thing is that this eror occurs randomly ( not all time ).

![corese_error](https://cloud.githubusercontent.com/assets/7684497/16557497/8327c4d6-41e0-11e6-807f-aa17f664049c.png)

Regards

Rachid

**Comment by ocorby** [comment]
Can you try to save copies of these ontologies on your computer and load 
them from the file system to see if it works ?

Olivier

**Comment by rac021** [comment]
Still getting the same error !

Regards 

Rachid

**Comment by rac021** [comment]
What I does is downloaded oboe ontologies on my local machine, changes URIs of these ontologies to relative path in "myOnto.owl" , this gives me the same error. 
But  when I load only oboe ontologies ( without myOnto.owl ) , the error disappears.

It seems that the problem comes from myOnto.owl ( in imports ?? )  but this is not what exception says.

Regards

Rachid

**Comment by rac021** [comment]
When I run 

**loader.load("http://ecoinformatics.org/oboe/oboe.1.0/oboe-core.owl")**

this **occasionally** gives me the error 

Regards

**Comment by ocorby** [comment]
Hi,

On 07/04/2016 02:27 PM, Yahiaoui Rachid wrote:
>
> When I run
>
> *loader.load("http://ecoinformatics.org/oboe/oboe.1.0/oboe-core.owl")*
>
> this *occasionally* gives me the error
>
The bug never occurs in my environment !
Can you try this from another Internet connection ?

Best regards,

Olivier

**Comment by ndelaforge** [comment]
@rac021 are you behind a proxy ?
Your proxy may not properly rewrite "application/owl+xml" or "application/rdf+xml" content type headers.

**Comment by rac021** [comment]
Hi,

I have not been able to reproduce the bug by changing connection, I think that the problem comes from my proxy, but as the error is random , I'll still try again to be sure.

Thank you @ocorby @ndelaforge 

Regards,

Rachid
