### ISSUE TITLE
Web server displays incorrect data on specific SPARQL endpoints

### ISSUE THREAD

**Issue by mateofatas** [Wimmics/corese#192]
**Issue Description:**

When creating multiple SPARQL endpoints on the Corese web server (as explained on the [Corse-server tutorial](https://github.com/Wimmics/corese/blob/master/docs/getting%20started/Getting%20Started%20With%20Corese-server.md#getting-started-with-corese-server)), the web-server at any endpoint will always display the default endpoint's data, and not the data which was assigned to that specific endpoint. 

**Bug Details:**

For example, let us create two SPARQL endpoints, the default one which displays data 'graph.ttl' (some predetermined TURTLE file) and another endpoint 'graph2' which is meant to display some other file's data 'graph2.ttl'. When we open these two endpoints on the web server at http://localhost:8080/sparql and http://localhost:8080/graph2/sparql, we should see the data from graph.ttl and the data from graph2.ttl respectively. However, this is not the case. At both endpoints, the default data is shown. 

If, however, you decide to get the data using http requests (either through python requests or curl) with SPARQL queries, the correct data is returned (e.g 'graph2.ttl' data is returned at http://localhost:8080/graph2/sparql). Therefore it is only an issue with what is _displayed_ on the web server.

**Steps to Reproduce:**

1. Create multiple endpoints by loading a profile into a local corese web server, as described in the [corse-server tutorial](https://github.com/Wimmics/corese/blob/master/docs/getting%20started/Getting%20Started%20With%20Corese-server.md#31-create-multiple-endpoints). 

**Expected Behavior:**

When visiting the different endpoints on the corese web server, you should be able to see the data that you assigned to that specific endpoint.

**Actual Behavior:**

At ALL endpoints, you see the data which was assigned to the default endpoint. The data which was assigned to specific endpoints is nowhere to be found.

**Screenshots/Attachments:**

Example Profile Code:
<img width="571" alt="image" src="https://github.com/Wimmics/corese/assets/174340894/b6e1f6a7-2bab-4464-9f1d-c8aeae0a68cf">

Corese web server at default endpoint (displaying correct data):
<img width="632" alt="image" src="https://github.com/Wimmics/corese/assets/174340894/2ddaec01-b3f7-45df-ba24-1ee5144c9c13">

Corese web server at http://localhost:8080/graph2/sparql (data is identical to default endpoint):
<img width="646" alt="image" src="https://github.com/Wimmics/corese/assets/174340894/e3276256-7841-4771-9388-c34cd7bf53c3">

Graph2.ttl (the data which should be displayed at the 'graph2' endpoint:
<img width="502" alt="image" src="https://github.com/Wimmics/corese/assets/174340894/ee1eb461-3a71-4767-a288-91e8c51c8f1e">

Python HTTP requests code for 'graph2' endpoint:
![image](https://github.com/Wimmics/corese/assets/174340894/2bd9f6d1-0cf8-481c-a67e-7ff61c878c02)

What the request returns (correct data which was never displayed on the corese web server):
![image](https://github.com/Wimmics/corese/assets/174340894/36db1edb-a2ea-43d3-ae1c-7b589f17dcbc)

**Comment by remiceres** [comment]
Matéo,

Thank you for your detailed issue report. We have reproduced the bug where all SPARQL endpoints display the default data on the web server, although HTTP requests return the correct data. We will work on a fix.

**Comment by remiceres** [comment]
Thank you for your report. The bug has been fixed and will be included in the next release of Corese. It is already available in the latest nightly build: [Corese Releases](https://github.com/Wimmics/corese/releases).
