### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by cmader** [Wimmics/corese#27]
License is only stated as a bullet point in the Readme, which is a little bit hidden. Maybe consider a separate "License" file in the main git repo which is afaik the best practice. Otherwise: I like the sparql template tool, great work!!!

**Comment by ocorby** [comment]
It is distributed with CeCILL-C licence (aka LGPL)

http://www.cecill.info/licences/Licence_CeCILL-C_V1-en.html

Olivier
