### ISSUE TITLE
Get only infered triples with Corese 

### ISSUE THREAD

**Issue by rac021** [Wimmics/corese#28]
Hi ,

is there a way to get only infered triples with corese ?

Thank's

R

**Comment by ocorby** [comment]
Hi,

On 09/24/2017 02:48 AM, Yahiaoui Rachid wrote:
>
> is there a way to get only infered triples with corese ?
>
Yes

rdfs entailment :

select *
from kg:entailment
where { ?x ?p ?y }

inference rules entailment:

select *
from kg:rule
where { ?x ?p ?y }

Best regards,


Olivier Corby

**Comment by rac021** [comment]
Thank you @ocorby 

I'll try this

Best regards

R

**Comment by rac021** [comment]
This exactly what I'm looking for. 

Thank you @ocorby 

R

**Comment by rac021** [comment]
When I try to obtain only inferred triples using  **SELECT * FROM kg:entailment WHERE { ?x ?p ?y }** 

This gives me also already loaded triples. Is this the expected behavior ?

Thank you

R

**Comment by ocorby** [comment]
Hi, 

Some existing triples may be also inferred. 
You can select infered triples : 

select * 
where { 
graph kg:entailment { ?x ?p ?y } 
filter not exists { graph ?g { ?x ?p ?y } filter (?g != kg:entailment) } 
} 

Olivier 

----- Mail original -----

**Comment by rac021** [comment]
Great ! 

Thank you @ocorby 

R
