### ISSUE TITLE
SPARQL endpoint URL

### ISSUE THREAD

**Issue by szarnyasg** [Wimmics/corese#3]
Hi,

I'm trying to use Corese for calculating some graph metrics (e.g. diameter) for a research project, the [Train Benchmark](https://github.com/FTSRG/trainbenchmark). I'd like to use the SPARQL endpoint from an [R script](https://github.com/szarnyasg/ida/blob/master/query.R). I started the Corese server with `java -jar corese-server-3.1.8.jar` but couldn't figure out the URL for the SPARQL endpoint. Can you please give me a pointer on that?

Thanks,
Gabor

**Comment by ndelaforge** [comment]
You ha

**Comment by szarnyasg** [comment]
Thanks for the quick reply! :+1: I tried that but with an empty database, my client library gave funny results :-). The endpoint works fine.
