### ISSUE TITLE
No documentation found on running from sources

### ISSUE THREAD

**Issue by jmvanel** [Wimmics/corese#30]
What do fo after 
```shell
mvm install 
```
to start locally the equivalent of http://corese.inria.fr/ ?

```shell
mvn tomcat:run
```
 does *not* start a server.

**Comment by remiceres** [comment]
Hello,

Apologies for not responding to your issue earlier. Given that this issue dates back to 2017, I'll answer it now as it may help other users.

1. Download the source code and compile:

```shell
git clone "https://github.com/Wimmics/corese.git"
cd corese
mvn clean install -DskipTests
```

2. Move to the target directory: 

```sh
cd corese-server/target/
```

3. Start the server:

```sh
java -jar -Dfile.encoding=UTF8 corese-server-4.4.1.jar
```

You can find documentation in the [project's readme](https://github.com/Wimmics/corese/blob/master/README.md) or in the [docs directory](https://github.com/Wimmics/corese/tree/master/docs).

Best regards,
Rémi
