### ISSUE TITLE
Loading same JSON-LD as file or proxied from other server does not work the same

### ISSUE THREAD

**Issue by frmichel** [Wimmics/corese#34]
Hi again,

Quite a weird one, still with standalone corese-3.2.3a.jar

The following loads and expanded JSON-LD file (with no @context) in compact form :
load <https://erebe-vm2.i3s.unice.fr/~fmichel/flickr-compact.jsonld>
That works fine.

The following loads exactly the same JSON-LD content although it is proxied from another server.
load <https://erebe-vm2.i3s.unice.fr/~fmichel/JsonLD-php/compact-jsonld-flickr.php>
It returns this error:
```
11:18:33.086 [Thread-3] ERROR fr.inria.edelweiss.kgraph.query.GraphManager - Load error: https://erebe-vm2.i3s.unice.fr/~fmichel/JsonLD-php/compact-jsonld-flickr.php
fr.com.hp.hpl.jena.rdf.arp.ParseException {E301} Content is not allowed in prolog.
line 1 in 'https://erebe-vm2.i3s.unice.fr/~fmichel/JsonLD-php/compact-jsonld-flickr.php'
https://erebe-vm2.i3s.unice.fr/~fmichel/JsonLD-php/compact-jsonld-flickr.php
11:18:33.086 [Thread-3] ERROR fr.inria.edelweiss.kgram.core.Exp - Load error: https://erebe-vm2.i3s.unice.fr/~fmichel/JsonLD-php/compact-jsonld-flickr.php
fr.com.hp.hpl.jena.rdf.arp.ParseException {E301} Content is not allowed in prolog.
line 1 in 'https://erebe-vm2.i3s.unice.fr/~fmichel/JsonLD-php/compact-jsonld-flickr.php'
https://erebe-vm2.i3s.unice.fr/~fmichel/JsonLD-php/compact-jsonld-flickr.php
** Time : 1.468
```
In both cases, the Content-Type header is "application/ld+json". But other HTTP headers differ.

Could you help me understand what's wrong in the second case?

Franck.

**Comment by ocorby** [comment]
On 11/28/2017 11:21 AM, Franck Michel wrote:
> The following loads exactly the same JSON-LD content although it is 
> proxied from another server.
> load 
> https://erebe-vm2.i3s.unice.fr/~fmichel/JsonLD-php/compact-jsonld-flickr.php 
> <https://erebe-vm2.i3s.unice.fr/%7Efmichel/JsonLD-php/compact-jsonld-flickr.php>
L'extension .php n'est peut être pas reconnue ici ?

Olivier

**Comment by frmichel** [comment]
> L'extension .php n'est peut être pas reconnue ici ?

Oui possible, à voir dans le code.
On pourrait imaginer que pour un fichier dans le FS local (file://...) 
on se base sur l'extension, mais dans le cas d'un fichier obtenu du 
réseau on tienne compte du Content-type en priorité s'il existe (en tout 
cas dans le cas http), de l'extension dans le cas contraire.

Franck.

Le 28/11/2017 à 12:07, ocorby a écrit :

**Comment by ocorby** [comment]
On 11/28/2017 12:18 PM, Franck Michel wrote:
> On pourrait imaginer que pour un fichier dans le FS local (file://...)
> on se base sur l'extension, mais dans le cas d'un fichier obtenu du
> réseau on tienne compte du Content-type en priorité s'il existe (en tout
> cas dans le cas http), de l'extension dans le cas contraire.
Normalement j'en tiens compte, mais peut être pas avec json :-) Je vais 
regarder.

Olivier
