### ISSUE TITLE
Corese won't load JSON file with http Link header pointing to JSON-LD context

### ISSUE THREAD

**Issue by frmichel** [Wimmics/corese#35]
Hi, last one for today ;)

Still using standalone corese-3.2.3a.jar

URL http://erebe-vm2.i3s.unice.fr/jsonld-proxy/flickr.json returns a JSON file along with headers:

```
Content-Type: application/json
Link: <http://erebe-vm2.i3s.unice.fr/~fmichel/flickr-profile.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"
```
According to the [specification](https://json-ld.org/spec/latest/json-ld/#interpreting-json-as-json-ld) this should be interpreted as regular JSON-LD, although the context has to be loaded from another file.

In Corese, command
`LOAD <http://erebe-vm2.i3s.unice.fr/jsonld-proxy/flickr.json>`
seems not to load anything: the triple store remains empty.
No error is displayed from Corese.

Franck.

**Comment by VladimirAlexiev** [comment]
@frmichel the new spec  https://www.w3.org/TR/json-ld11/#example-142-referencing-a-json-ld-context-from-a-json-document-via-an-http-link-header says  JSON-LD documents served with the application/ld+json media type MUST have all context information, including references to external contexts, within the body of the document. Contexts linked via a http://www.w3.org/ns/json-ld#context HTTP Link Header MUST be ignored for such documents.

I think it's some security related restriction
