### ISSUE TITLE
following error when i build my docker images

### ISSUE THREAD

**Issue by Ahmedko** [Wimmics/corese#38]
Dear all,

I'm sorry could you help me ?

I have an error when, i try to build a docker images, the error is related to a dependencies : 

My DockerFile is available through this following link
https://github.com/Ahmedko/Corese/tree/master

<img width="959" alt="sans titre" src="https://user-images.githubusercontent.com/25797261/34125579-fe1f9962-e436-11e7-9214-0daa6bc33762.png">

Thank you in advance

**Comment by ErwanDemairy** [comment]
Hello,
I pushed a correction and a Dockerfile at https://github.com/Wimmics/corese/blob/master/kgserver/Dockerfile : it builds the container and launch the server at startup.
This is based on fedora, but the translation to centos should be straightforward.
Best regards,
Erwan

**Comment by ErwanDemairy** [comment]
I uploaded the docker image to gitlab inria, so you can use:
docker run registry.gitlab.inria.fr/scagram/corese/corese_server
Best regards,
Erwan

**Comment by Ahmedko** [comment]
Thanks ^^
Regards

**Comment by Ahmedko** [comment]
Dear,

i still and error, but now it's  coresedb-benchmark, May is related my docker? i'm going to investigated in that problem using simple install on command line. 

![image](https://user-images.githubusercontent.com/25797261/34960748-85a6b4c2-fa3c-11e7-8c01-a2e07cd60cd4.png)

Thank you,

**Comment by ErwanDemairy** [comment]
Hello,
I made a bit of cleaning in the repository, and you should not have this problem anymore with the last version committed (git hash : c89a101ca5106592083c0378ade2b06d03911ef6 )
Best regards,
Erwan Demairy

**Comment by Ahmedko** [comment]
Thank you a lot of Erwan.
