### ISSUE TITLE
loading multiple files

### ISSUE THREAD

**Issue by echo66** [Wimmics/corese#6]
Greetings! I have the following files (output of ls -l):

-rw-rw-rw- 1 echo66 echo66    77509 Fev  6 19:14 bio.rdf
-rw-rw-rw- 1 echo66 echo66    98354 Fev  6 17:29 dcterms.rdf
-rw-rw-r-- 1 echo66 echo66     5908 Ago 23  2010 event.n3
-rw-rw-rw- 1 echo66 echo66    41949 Fev  6 17:30 foaf.rdf
-rw-rw-rw- 1 echo66 echo66   107153 Fev  6 17:31 frbr.rdf
-rw-rw-rw- 1 echo66 echo66 67547571 Fev  6 19:08 jamendo.n3
-rw-rw-rw- 1 echo66 echo66    12885 Fev  6 17:32 keys.rdf
-rw-rw-rw- 1 echo66 echo66   104284 Fev  6 17:18 mo.n3
-rw-rw-rw- 1 echo66 echo66    26372 Fev  6 17:17 timeline.n3
-rw-rw-rw- 1 echo66 echo66    10172 Fev  6 17:32 wgs84_pos.rdf

When I run corese server with the following command

java -jar corese-server-3.1.8.jar -e -o --load my-dir/

it does not load all N3 files in the server. If I perform a counting query with 

select (COUNT(*) AS ?count) where {
    ?x ?p ?y .
}

the output is 6420. But jamendo.n3 has, at least, 10 million triples...

EDIT: I compiled the current version (3.2.1) and concluded that this issue exists in both Corese releases.

**Comment by ocorby** [comment]
Hello,

On 02/06/2016 08:20 PM, echo66 wrote:
>
> it does not load all N3 files in the server.
>
Yes we do not yet tackle the .n3 extension, use .nt instead.

Regards,

Olivier Corby

**Comment by echo66** [comment]
Thanks! The file extension seems to be the issue.
