### ISSUE TITLE
URL-encoded POST // Encountered "update" at line 1, column 1

### ISSUE THREAD

**Issue by Inexpugnable** [Wimmics/corese#70]
Issue raised when using Corese-server (version 4.1.4a) and SPARQLWrapper (python library) with insert queries (not tested with other SPARQL 1.1 Update queries).

SPARQLWrapper will detect that Corese-server uses the "URL-encoded" protocol (https://www.w3.org/TR/sparql11-protocol/#update-operation) and will therefore use an "update" parameter not supported by Corese-server.

Line of codes probably involved in SPARQLWrapper (https://github.com/RDFLib/sparqlwrapper/blob/master/SPARQLWrapper/Wrapper.py):
```
request = urllib.request.Request(uri)
request.add_header("Content-Type", "application/x-www-form-urlencoded")
request.data = self._getRequestEncodedParameters(("update", self.queryString)).encode('ascii')
```

One way to workaround the problem with SPARQLWrapper is to use the parameter  'postdirectly' (setRequestMethod('postdirectly')) https://sparqlwrapper.readthedocs.io/en/latest/SPARQLWrapper.Wrapper.html#SPARQLWrapper.Wrapper.POSTDIRECTLY

**Comment by MaillPierre** [comment]
Tested during resolution of #191
