### ISSUE TITLE
Query rewriting prefixes with insert / Service

### ISSUE THREAD

**Issue by Inexpugnable** [Wimmics/corese#72]
Issue encountered with the endpoint "https://www.navigae.fr/repositories/Navigae".

Query used to reproduce the issue.
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX schema: <http://schema.org/>
INSERT {
    ?x owl:sameAs ?uri.
    ?uri owl:sameAs ?x
} WHERE {
  SERVICE <https://www.navigae.fr/repositories/Navigae> {
    ?x (owl:sameAs|^owl:sameAs|skos:exactMatch|^skos:exactMatch|owl:equivalentClass|^owl:equivalentClass|owl:equivalentProperty|^owl:equivalentProperty|schema:sameAs|^schema:sameAs)+ ?y.
  }
  BIND(URI(?y) as ?uri)
}

Even if this query does not return any result on "https://www.navigae.fr/repositories/Navigae", the query rewriting system ignores the skos prefix, leading to a 400 error.

Errors throw by Corese :
ERROR query.ProviderImpl.send:488
java.io.IOException: Server returned HTTP response code: 400 for URL: https://www.navigae.fr/repositories/Navigae

**Comment by ocorby** [comment]
The correct query would be with <> :

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX schema: <http://schema.org/>
INSERT {
?x owl:sameAs ?uri.
?uri owl:sameAs ?x
} WHERE {
SERVICE <https://www.navigae.fr/repositories/Navigae> {
?x 
(owl:sameAs|^owl:sameAs|skos:exactMatch|^skos:exactMatch|owl:equivalentClass|^owl:equivalentClass|owl:equivalentProperty|^owl:equivalentProperty|schema:sameAs|^schema:sameAs)+ 
?y.
}
BIND(URI(?y) as ?uri)
}


It seems that the endpoint does not accept SPARQL Update

If you replace insert by select there is no error.

Olivier

**Comment by Inexpugnable** [comment]
Indeed, I miscopied the <>.

Thanks for the feedback it's good to know that some endpoints do not support SPARQL UPDATE I will adapt my queries accordingly.
