### ISSUE TITLE
org.xml.sax.SAXParseException; Premature end of file (service clause on BioKB)

### ISSUE THREAD

**Issue by Inexpugnable** [Wimmics/corese#74]
The following query return org.xml.sax.SAXParseException; Premature end of file.
```
select * 
where {
  service <http://biokb.lcsb.uni.lu/sparql> {
    <http://purl.obolibrary.org/obo/NCBITaxon_197159> ?p ?y
  }
}
```

**Comment by ocorby** [comment]
On 10/26/20 8:34 AM, Inexpugnable wrote:
>
> The following query return org.xml.sax.SAXParseException; Premature 
> end of file.
>
> |select * where { service <http://biokb.lcsb.uni.lu/sparql> { 
> <http://purl.obolibrary.org/obo/NCBITaxon_197159> ?p ?y } } |
|Use service clause with https :|

|select * where { service <https://biokb.lcsb.uni.lu/sparql> { 
<http://purl.obolibrary.org/obo/NCBITaxon_197159> ?p ?y } }|

**Comment by Inexpugnable** [comment]
Sweet! Thank you for the help!

**Comment by Inexpugnable** [comment]
Hello,

I maybe found out an issue related to this one.

The following query returns: org.xml.sax.SAXParseException; lineNumber: 20; columnNumber: 24; Element or attribute do not match QName production: QName::=(NCName':')?NCName.

```
PREFIX void: <http://rdfs.org/ns/void#>  
SELECT * where {
  SERVICE <http://void.rkbexplorer.com/sparql> {
    ?URIDataset a void:Dataset .
    ?URIDataset void:sparqlEndpoint ?endpoint
  }
}
```

This time adding https doesn't seem to help since I get the following error after modification:
javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
